# Generated by Django 5.1.6 on 2025-07-07 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('case_completed', 'Case Completed'), ('quiz_taken', 'Quiz Taken'), ('anatomy_explored', 'Anatomy Explored'), ('ai_checker_used', 'AI Checker Used'), ('achievement_earned', 'Achievement Earned'), ('level_up', 'Level Up'), ('login', 'Login'), ('profile_updated', 'Profile Updated')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('xp_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('year_of_study', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('resident', 'Resident'), ('other', 'Other')], default='1', max_length=10)),
                ('specialization', models.CharField(choices=[('general', 'General Medicine'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('surgery', 'Surgery'), ('psychiatry', 'Psychiatry'), ('emergency', 'Emergency Medicine'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('other', 'Other')], default='general', max_length=20)),
                ('total_xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('cases_completed', models.IntegerField(default=0)),
                ('quiz_accuracy', models.FloatField(default=0.0)),
                ('total_study_time', models.IntegerField(default=0)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('public_profile', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('activities_completed', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('case_master', 'Case Master'), ('quiz_expert', 'Quiz Expert'), ('streak_7', 'Week Warrior'), ('streak_30', 'Month Master'), ('anatomy_explorer', 'Anatomy Explorer'), ('ai_user', 'AI User'), ('level_up', 'Level Up'), ('first_case', 'First Case'), ('perfect_quiz', 'Perfect Quiz'), ('early_bird', 'Early Bird'), ('night_owl', 'Night Owl')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('xp_reward', models.IntegerField(default=0)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement_type')},
            },
        ),
    ]
