# Generated by Django 5.2.4 on 2025-07-13 11:13

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='timed_challenges_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('case_master', 'Case Master'), ('quiz_expert', 'Quiz Expert'), ('streak_7', 'Week Warrior'), ('streak_30', 'Month Master'), ('anatomy_explorer', 'Anatomy Explorer'), ('ai_user', 'AI User'), ('level_up', 'Level Up'), ('first_case', 'First Case'), ('perfect_quiz', 'Perfect Quiz'), ('early_bird', 'Early Bird'), ('night_owl', 'Night Owl'), ('first_timed_challenge', 'First Timed Challenge')], max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(default=core.models.generate_student_id, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='TimedChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('time_taken', models.IntegerField()),
                ('xp_earned', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
