# Generated by Django 5.1.6 on 2025-07-07 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='heart', max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnatomyStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('function', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('model_3d_url', models.URLField(blank=True)),
                ('xp_reward', models.IntegerField(default=10)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='anatomy.anatomysystem')),
            ],
        ),
        migrations.CreateModel(
            name='AnatomyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('xp_earned', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anatomy.anatomystructure')),
            ],
            options={
                'unique_together': {('user', 'structure')},
            },
        ),
    ]
