# Generated by Django 5.2.4 on 2025-07-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='label',
            field=models.CharField(default='X', max_length=1),
        ),
    ]
