# Generated by Django 5.2.4 on 2025-07-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_choice_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='label',
            field=models.CharField(max_length=1),
        ),
    ]
